import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by supabase gen types — do not lint Supabase's type plumbing.
    "lib/supabase/database.types.ts",
  ]),
  {
    // Phase 1 type-safety gate. Enforced everywhere except the generated
    // Supabase types file (ignored above). If you reach for `any`, use
    // `unknown` and narrow, or write the real type.
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
]);

export default eslintConfig;
