/**
 * Seed catalog for pre-filling per-item à la carte dollar values.
 *
 * This module is a static, bundled data source — no network, no backend.
 * Keep it free of external dependencies and side effects. See
 * `plans/robust-price-estimates.md` for the curation rationale.
 *
 * `valueLow` / `valueHigh` are a typical U.S. urban à la carte range — what a
 * sit-down restaurant would charge if the item were ordered as a single unit
 * from a regular menu (NOT a buffet-cost-equivalent). `typicalValue` is the
 * midpoint, rounded to a sensible increment.
 *
 * `fillFactor` follows the PLAN.md semantics: 1 = single shrimp,
 * 10 = whole pizza. Most sushi pieces are 1–2, KBBQ cuts 4–6, a full entrée
 * plate 7–9, a whole pizza 10.
 */

export type Cuisine =
  | "kbbq"
  | "sushi"
  | "chinese"
  | "dimsum"
  | "hotpot"
  | "brazilian"
  | "indian"
  | "pizza"
  | "seafood"
  | "dessert"
  | "other";

export interface SeedEntry {
  /** Stable slug, e.g. "kbbq.wagyu-short-rib". */
  id: string;
  /** Canonical display name. */
  name: string;
  /** Lowercased alternate names for matching. */
  aliases: string[];
  cuisine: Cuisine;
  /** Optional free-text category that maps to Item.category. */
  category?: string;
  /** USD midpoint. */
  typicalValue: number;
  /** USD lower bound of typical US urban à la carte. */
  valueLow: number;
  /** USD upper bound. */
  valueHigh: number;
  /** Integer in [1, 10]. */
  fillFactor: number;
  /** Grams per one serving unit. See docs/quantitative-appetite.md. */
  gramsPerUnit: number;
}

/** Cuisine priority order for tie-breaking `findSeedMatches` results. */
const CUISINE_PRIORITY: readonly Cuisine[] = [
  "kbbq",
  "sushi",
  "chinese",
  "dimsum",
  "hotpot",
  "brazilian",
  "indian",
  "pizza",
  "seafood",
  "dessert",
  "other",
];

const CUISINE_RANK: ReadonlyMap<Cuisine, number> = new Map(
  CUISINE_PRIORITY.map((c, i) => [c, i])
);

export const SEED_CATALOG: readonly SeedEntry[] = [
  // ─── KBBQ (Korean BBQ) ────────────────────────────────────────────────
  {
    id: "kbbq.wagyu-short-rib",
    name: "Wagyu Short Rib",
    aliases: ["wagyu galbi", "wagyu kalbi"],
    cuisine: "kbbq",
    category: "Beef",
    typicalValue: 22,
    valueLow: 18,
    valueHigh: 26,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "kbbq.prime-short-rib",
    name: "Prime Short Rib",
    aliases: ["usda prime short rib"],
    cuisine: "kbbq",
    category: "Beef",
    typicalValue: 17,
    valueLow: 14,
    valueHigh: 20,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "kbbq.la-galbi",
    name: "LA Galbi",
    aliases: ["la kalbi", "marinated short rib", "flanken ribs"],
    cuisine: "kbbq",
    category: "Beef",
    typicalValue: 18,
    valueLow: 15,
    valueHigh: 22,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "kbbq.marinated-galbi",
    name: "Marinated Galbi",
    aliases: ["marinated kalbi", "yangnyeom galbi"],
    cuisine: "kbbq",
    category: "Beef",
    typicalValue: 17,
    valueLow: 14,
    valueHigh: 20,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "kbbq.brisket",
    name: "Beef Brisket",
    aliases: ["brisket", "chadolbaegi", "chadol", "thin sliced brisket"],
    cuisine: "kbbq",
    category: "Beef",
    typicalValue: 13,
    valueLow: 11,
    valueHigh: 16,
    fillFactor: 4,
    gramsPerUnit: 150,
  },
  {
    id: "kbbq.bulgogi",
    name: "Bulgogi",
    aliases: ["marinated beef", "beef bulgogi"],
    cuisine: "kbbq",
    category: "Beef",
    typicalValue: 16,
    valueLow: 13,
    valueHigh: 19,
    fillFactor: 6,
    gramsPerUnit: 150,
  },
  {
    id: "kbbq.beef-tongue",
    name: "Beef Tongue",
    aliases: ["uhyeo", "woo hyeo", "tongue"],
    cuisine: "kbbq",
    category: "Beef",
    typicalValue: 15,
    valueLow: 12,
    valueHigh: 18,
    fillFactor: 4,
    gramsPerUnit: 100,
  },
  {
    id: "kbbq.ribeye",
    name: "Ribeye",
    aliases: ["rib eye", "kkot deungshim"],
    cuisine: "kbbq",
    category: "Beef",
    typicalValue: 20,
    valueLow: 16,
    valueHigh: 24,
    fillFactor: 6,
    gramsPerUnit: 150,
  },
  {
    id: "kbbq.sirloin",
    name: "Sirloin",
    aliases: ["deungshim"],
    cuisine: "kbbq",
    category: "Beef",
    typicalValue: 16,
    valueLow: 13,
    valueHigh: 19,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "kbbq.hanger-steak",
    name: "Hanger Steak",
    aliases: ["toshisal", "anchang sal"],
    cuisine: "kbbq",
    category: "Beef",
    typicalValue: 17,
    valueLow: 14,
    valueHigh: 20,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "kbbq.pork-belly",
    name: "Pork Belly",
    aliases: ["samgyeopsal", "samgyupsal"],
    cuisine: "kbbq",
    category: "Pork",
    typicalValue: 15,
    valueLow: 12,
    valueHigh: 18,
    fillFactor: 6,
    gramsPerUnit: 150,
  },
  {
    id: "kbbq.thick-pork-belly",
    name: "Thick Cut Pork Belly",
    aliases: ["thick pork belly", "ogyeopsal"],
    cuisine: "kbbq",
    category: "Pork",
    typicalValue: 17,
    valueLow: 14,
    valueHigh: 20,
    fillFactor: 6,
    gramsPerUnit: 160,
  },
  {
    id: "kbbq.spicy-pork",
    name: "Spicy Pork",
    aliases: ["dwaeji bulgogi", "spicy pork bulgogi"],
    cuisine: "kbbq",
    category: "Pork",
    typicalValue: 15,
    valueLow: 12,
    valueHigh: 18,
    fillFactor: 6,
    gramsPerUnit: 150,
  },
  {
    id: "kbbq.pork-jowl",
    name: "Pork Jowl",
    aliases: ["hangjeongsal", "pork cheek"],
    cuisine: "kbbq",
    category: "Pork",
    typicalValue: 15,
    valueLow: 12,
    valueHigh: 18,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "kbbq.chicken-thigh",
    name: "Marinated Chicken Thigh",
    aliases: ["chicken thigh", "marinated chicken", "dakgalbi", "chicken bulgogi"],
    cuisine: "kbbq",
    category: "Chicken",
    typicalValue: 14,
    valueLow: 11,
    valueHigh: 17,
    fillFactor: 6,
    gramsPerUnit: 150,
  },
  {
    id: "kbbq.gopchang",
    name: "Gopchang",
    aliases: ["beef intestine", "small intestine"],
    cuisine: "kbbq",
    category: "Offal",
    typicalValue: 18,
    valueLow: 15,
    valueHigh: 22,
    fillFactor: 5,
    gramsPerUnit: 100,
  },
  {
    id: "kbbq.daechang",
    name: "Daechang",
    aliases: ["large intestine"],
    cuisine: "kbbq",
    category: "Offal",
    typicalValue: 18,
    valueLow: 15,
    valueHigh: 22,
    fillFactor: 5,
    gramsPerUnit: 100,
  },
  {
    id: "kbbq.yangnyeom-galbi",
    name: "Yangnyeom Galbi",
    aliases: ["seasoned short rib"],
    cuisine: "kbbq",
    category: "Beef",
    typicalValue: 17,
    valueLow: 14,
    valueHigh: 20,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "kbbq.japchae",
    name: "Japchae",
    aliases: ["glass noodle stir fry", "sweet potato noodles"],
    cuisine: "kbbq",
    category: "Side",
    typicalValue: 10,
    valueLow: 8,
    valueHigh: 13,
    fillFactor: 6,
    gramsPerUnit: 180,
  },
  {
    id: "kbbq.kimchi",
    name: "Kimchi",
    aliases: ["fermented cabbage"],
    cuisine: "kbbq",
    category: "Banchan",
    typicalValue: 4,
    valueLow: 3,
    valueHigh: 6,
    fillFactor: 2,
    gramsPerUnit: 50,
  },
  {
    id: "kbbq.kimchi-jjigae",
    name: "Kimchi Jjigae",
    aliases: ["kimchi stew"],
    cuisine: "kbbq",
    category: "Stew",
    typicalValue: 13,
    valueLow: 10,
    valueHigh: 16,
    fillFactor: 7,
    gramsPerUnit: 350,
  },
  {
    id: "kbbq.doenjang-jjigae",
    name: "Doenjang Jjigae",
    aliases: ["soybean paste stew"],
    cuisine: "kbbq",
    category: "Stew",
    typicalValue: 12,
    valueLow: 10,
    valueHigh: 15,
    fillFactor: 7,
    gramsPerUnit: 350,
  },
  {
    id: "kbbq.soondubu",
    name: "Soondubu Jjigae",
    aliases: ["soondubu", "sundubu", "soft tofu stew"],
    cuisine: "kbbq",
    category: "Stew",
    typicalValue: 13,
    valueLow: 11,
    valueHigh: 16,
    fillFactor: 7,
    gramsPerUnit: 350,
  },
  {
    id: "kbbq.bibimbap",
    name: "Bibimbap",
    aliases: ["stone pot rice", "dolsot bibimbap"],
    cuisine: "kbbq",
    category: "Rice",
    typicalValue: 14,
    valueLow: 12,
    valueHigh: 17,
    fillFactor: 8,
    gramsPerUnit: 450,
  },
  {
    id: "kbbq.steamed-egg",
    name: "Steamed Egg",
    aliases: ["gyeran jjim"],
    cuisine: "kbbq",
    category: "Side",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 3,
    gramsPerUnit: 200,
  },

  // ─── Sushi ───────────────────────────────────────────────────────────
  {
    id: "sushi.salmon-nigiri",
    name: "Salmon Nigiri",
    aliases: ["sake nigiri", "sake"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 4,
    valueLow: 3,
    valueHigh: 5.5,
    fillFactor: 2,
    gramsPerUnit: 20,
  },
  {
    id: "sushi.tuna-nigiri",
    name: "Tuna Nigiri",
    aliases: ["maguro nigiri", "maguro"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 4.5,
    valueLow: 3.5,
    valueHigh: 6,
    fillFactor: 2,
    gramsPerUnit: 20,
  },
  {
    id: "sushi.yellowtail-nigiri",
    name: "Yellowtail Nigiri",
    aliases: ["hamachi nigiri", "hamachi", "buri"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 6.5,
    fillFactor: 2,
    gramsPerUnit: 20,
  },
  {
    id: "sushi.shrimp-nigiri",
    name: "Shrimp Nigiri",
    aliases: ["ebi nigiri", "ebi"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 3.5,
    valueLow: 2.5,
    valueHigh: 5,
    fillFactor: 1,
    gramsPerUnit: 20,
  },
  {
    id: "sushi.sweet-shrimp-nigiri",
    name: "Sweet Shrimp Nigiri",
    aliases: ["amaebi", "amaebi nigiri"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 1,
    gramsPerUnit: 20,
  },
  {
    id: "sushi.eel-nigiri",
    name: "Eel Nigiri",
    aliases: ["unagi nigiri", "unagi"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 5.5,
    valueLow: 4.5,
    valueHigh: 7,
    fillFactor: 2,
    gramsPerUnit: 20,
  },
  {
    id: "sushi.sea-urchin-nigiri",
    name: "Sea Urchin Nigiri",
    aliases: ["uni", "uni nigiri"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 9,
    valueLow: 7,
    valueHigh: 12,
    fillFactor: 1,
    gramsPerUnit: 15,
  },
  {
    id: "sushi.salmon-roe-nigiri",
    name: "Salmon Roe Nigiri",
    aliases: ["ikura", "ikura nigiri"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 1,
    gramsPerUnit: 15,
  },
  {
    id: "sushi.flying-fish-roe-nigiri",
    name: "Flying Fish Roe Nigiri",
    aliases: ["tobiko nigiri", "tobiko"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 6.5,
    fillFactor: 1,
    gramsPerUnit: 15,
  },
  {
    id: "sushi.fatty-tuna-nigiri",
    name: "Fatty Tuna Nigiri",
    aliases: ["toro", "toro nigiri", "otoro", "chutoro"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 9,
    valueLow: 7,
    valueHigh: 14,
    fillFactor: 2,
    gramsPerUnit: 20,
  },
  {
    id: "sushi.mackerel-nigiri",
    name: "Mackerel Nigiri",
    aliases: ["saba nigiri", "saba"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 4,
    valueLow: 3,
    valueHigh: 5.5,
    fillFactor: 2,
    gramsPerUnit: 20,
  },
  {
    id: "sushi.octopus-nigiri",
    name: "Octopus Nigiri",
    aliases: ["tako nigiri", "tako"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 4.5,
    valueLow: 3.5,
    valueHigh: 6,
    fillFactor: 2,
    gramsPerUnit: 20,
  },
  {
    id: "sushi.squid-nigiri",
    name: "Squid Nigiri",
    aliases: ["ika nigiri", "ika"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 4,
    valueLow: 3,
    valueHigh: 5.5,
    fillFactor: 2,
    gramsPerUnit: 20,
  },
  {
    id: "sushi.scallop-nigiri",
    name: "Scallop Nigiri",
    aliases: ["hotate nigiri", "hotate"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 5.5,
    valueLow: 4.5,
    valueHigh: 7,
    fillFactor: 1,
    gramsPerUnit: 20,
  },
  {
    id: "sushi.egg-nigiri",
    name: "Egg Nigiri",
    aliases: ["tamago nigiri", "tamago"],
    cuisine: "sushi",
    category: "Nigiri",
    typicalValue: 3,
    valueLow: 2,
    valueHigh: 4,
    fillFactor: 2,
    gramsPerUnit: 25,
  },
  {
    id: "sushi.salmon-sashimi",
    name: "Salmon Sashimi",
    aliases: ["sake sashimi"],
    cuisine: "sushi",
    category: "Sashimi",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 1,
    gramsPerUnit: 15,
  },
  {
    id: "sushi.tuna-sashimi",
    name: "Tuna Sashimi",
    aliases: ["maguro sashimi"],
    cuisine: "sushi",
    category: "Sashimi",
    typicalValue: 5.5,
    valueLow: 4.5,
    valueHigh: 7.5,
    fillFactor: 1,
    gramsPerUnit: 15,
  },
  {
    id: "sushi.yellowtail-sashimi",
    name: "Yellowtail Sashimi",
    aliases: ["hamachi sashimi"],
    cuisine: "sushi",
    category: "Sashimi",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 1,
    gramsPerUnit: 15,
  },
  {
    id: "sushi.california-roll",
    name: "California Roll",
    aliases: ["cali roll", "sushi roll", "sushi"],
    cuisine: "sushi",
    category: "Roll",
    typicalValue: 8,
    valueLow: 6,
    valueHigh: 10,
    fillFactor: 5,
    gramsPerUnit: 180,
  },
  {
    id: "sushi.spicy-tuna-roll",
    name: "Spicy Tuna Roll",
    aliases: [],
    cuisine: "sushi",
    category: "Roll",
    typicalValue: 9,
    valueLow: 7,
    valueHigh: 12,
    fillFactor: 5,
    gramsPerUnit: 180,
  },
  {
    id: "sushi.spicy-salmon-roll",
    name: "Spicy Salmon Roll",
    aliases: [],
    cuisine: "sushi",
    category: "Roll",
    typicalValue: 9,
    valueLow: 7,
    valueHigh: 12,
    fillFactor: 5,
    gramsPerUnit: 180,
  },
  {
    id: "sushi.rainbow-roll",
    name: "Rainbow Roll",
    aliases: [],
    cuisine: "sushi",
    category: "Roll",
    typicalValue: 14,
    valueLow: 11,
    valueHigh: 17,
    fillFactor: 6,
    gramsPerUnit: 220,
  },
  {
    id: "sushi.dragon-roll",
    name: "Dragon Roll",
    aliases: [],
    cuisine: "sushi",
    category: "Roll",
    typicalValue: 14,
    valueLow: 11,
    valueHigh: 18,
    fillFactor: 6,
    gramsPerUnit: 220,
  },
  {
    id: "sushi.caterpillar-roll",
    name: "Caterpillar Roll",
    aliases: [],
    cuisine: "sushi",
    category: "Roll",
    typicalValue: 13,
    valueLow: 10,
    valueHigh: 16,
    fillFactor: 6,
    gramsPerUnit: 220,
  },
  {
    id: "sushi.philadelphia-roll",
    name: "Philadelphia Roll",
    aliases: ["philly roll"],
    cuisine: "sushi",
    category: "Roll",
    typicalValue: 9,
    valueLow: 7,
    valueHigh: 12,
    fillFactor: 5,
    gramsPerUnit: 180,
  },
  {
    id: "sushi.eel-avocado-roll",
    name: "Eel Avocado Roll",
    aliases: ["unagi avocado roll"],
    cuisine: "sushi",
    category: "Roll",
    typicalValue: 11,
    valueLow: 9,
    valueHigh: 14,
    fillFactor: 5,
    gramsPerUnit: 180,
  },
  {
    id: "sushi.tempura-shrimp-roll",
    name: "Shrimp Tempura Roll",
    aliases: ["tempura shrimp roll"],
    cuisine: "sushi",
    category: "Roll",
    typicalValue: 11,
    valueLow: 9,
    valueHigh: 14,
    fillFactor: 6,
    gramsPerUnit: 220,
  },
  {
    id: "sushi.spider-roll",
    name: "Spider Roll",
    aliases: ["soft shell crab roll"],
    cuisine: "sushi",
    category: "Roll",
    typicalValue: 13,
    valueLow: 10,
    valueHigh: 16,
    fillFactor: 6,
    gramsPerUnit: 220,
  },
  {
    id: "sushi.tuna-roll",
    name: "Tuna Roll",
    aliases: ["tekkamaki", "tekka maki"],
    cuisine: "sushi",
    category: "Roll",
    typicalValue: 7,
    valueLow: 5,
    valueHigh: 9,
    fillFactor: 4,
    gramsPerUnit: 180,
  },
  {
    id: "sushi.salmon-roll",
    name: "Salmon Roll",
    aliases: [],
    cuisine: "sushi",
    category: "Roll",
    typicalValue: 7,
    valueLow: 5,
    valueHigh: 9,
    fillFactor: 4,
    gramsPerUnit: 180,
  },
  {
    id: "sushi.cucumber-roll",
    name: "Cucumber Roll",
    aliases: ["kappa maki", "kappamaki"],
    cuisine: "sushi",
    category: "Roll",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 140,
  },
  {
    id: "sushi.avocado-roll",
    name: "Avocado Roll",
    aliases: [],
    cuisine: "sushi",
    category: "Roll",
    typicalValue: 6,
    valueLow: 4,
    valueHigh: 8,
    fillFactor: 3,
    gramsPerUnit: 140,
  },
  {
    id: "sushi.spicy-tuna-hand-roll",
    name: "Spicy Tuna Hand Roll",
    aliases: ["spicy tuna temaki"],
    cuisine: "sushi",
    category: "Hand Roll",
    typicalValue: 7,
    valueLow: 5,
    valueHigh: 9,
    fillFactor: 4,
    gramsPerUnit: 70,
  },
  {
    id: "sushi.salmon-hand-roll",
    name: "Salmon Hand Roll",
    aliases: ["salmon temaki"],
    cuisine: "sushi",
    category: "Hand Roll",
    typicalValue: 7,
    valueLow: 5,
    valueHigh: 9,
    fillFactor: 4,
    gramsPerUnit: 70,
  },
  {
    id: "sushi.yellowtail-scallion-hand-roll",
    name: "Yellowtail Scallion Hand Roll",
    aliases: ["hamachi negi hand roll", "negihama temaki"],
    cuisine: "sushi",
    category: "Hand Roll",
    typicalValue: 7,
    valueLow: 5,
    valueHigh: 9,
    fillFactor: 4,
    gramsPerUnit: 70,
  },
  {
    id: "sushi.edamame",
    name: "Edamame",
    aliases: ["soybeans"],
    cuisine: "sushi",
    category: "Appetizer",
    typicalValue: 6,
    valueLow: 4,
    valueHigh: 8,
    fillFactor: 3,
    gramsPerUnit: 120,
  },
  {
    id: "sushi.miso-soup",
    name: "Miso Soup",
    aliases: ["misoshiru"],
    cuisine: "sushi",
    category: "Soup",
    typicalValue: 4,
    valueLow: 3,
    valueHigh: 5,
    fillFactor: 3,
    gramsPerUnit: 240,
  },
  {
    id: "sushi.seaweed-salad",
    name: "Seaweed Salad",
    aliases: ["wakame salad", "wakame"],
    cuisine: "sushi",
    category: "Appetizer",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 3,
    gramsPerUnit: 80,
  },
  {
    id: "sushi.agedashi-tofu",
    name: "Agedashi Tofu",
    aliases: ["fried tofu"],
    cuisine: "sushi",
    category: "Appetizer",
    typicalValue: 7,
    valueLow: 5,
    valueHigh: 9,
    fillFactor: 4,
    gramsPerUnit: 150,
  },
  {
    id: "sushi.gyoza",
    name: "Gyoza",
    aliases: ["japanese dumplings", "pan fried dumplings"],
    cuisine: "sushi",
    category: "Appetizer",
    typicalValue: 7,
    valueLow: 5,
    valueHigh: 9,
    fillFactor: 4,
    gramsPerUnit: 25,
  },
  {
    id: "sushi.chicken-teriyaki",
    name: "Chicken Teriyaki",
    aliases: ["teriyaki chicken"],
    cuisine: "sushi",
    category: "Entree",
    typicalValue: 16,
    valueLow: 13,
    valueHigh: 20,
    fillFactor: 8,
    gramsPerUnit: 250,
  },

  // ─── Chinese Buffet ──────────────────────────────────────────────────
  {
    id: "chinese.general-tso-chicken",
    name: "General Tso's Chicken",
    aliases: ["general tso chicken", "general tsos chicken"],
    cuisine: "chinese",
    category: "Entree",
    typicalValue: 15,
    valueLow: 12,
    valueHigh: 18,
    fillFactor: 8,
    gramsPerUnit: 300,
  },
  {
    id: "chinese.orange-chicken",
    name: "Orange Chicken",
    aliases: [],
    cuisine: "chinese",
    category: "Entree",
    typicalValue: 14,
    valueLow: 11,
    valueHigh: 17,
    fillFactor: 8,
    gramsPerUnit: 300,
  },
  {
    id: "chinese.sesame-chicken",
    name: "Sesame Chicken",
    aliases: [],
    cuisine: "chinese",
    category: "Entree",
    typicalValue: 14,
    valueLow: 11,
    valueHigh: 17,
    fillFactor: 8,
    gramsPerUnit: 300,
  },
  {
    id: "chinese.beef-broccoli",
    name: "Beef and Broccoli",
    aliases: ["beef broccoli", "broccoli beef"],
    cuisine: "chinese",
    category: "Entree",
    typicalValue: 15,
    valueLow: 12,
    valueHigh: 18,
    fillFactor: 8,
    gramsPerUnit: 300,
  },
  {
    id: "chinese.kung-pao-chicken",
    name: "Kung Pao Chicken",
    aliases: ["gong bao chicken", "kung po chicken"],
    cuisine: "chinese",
    category: "Entree",
    typicalValue: 14,
    valueLow: 11,
    valueHigh: 17,
    fillFactor: 8,
    gramsPerUnit: 300,
  },
  {
    id: "chinese.mongolian-beef",
    name: "Mongolian Beef",
    aliases: [],
    cuisine: "chinese",
    category: "Entree",
    typicalValue: 16,
    valueLow: 13,
    valueHigh: 19,
    fillFactor: 8,
    gramsPerUnit: 300,
  },
  {
    id: "chinese.sweet-sour-pork",
    name: "Sweet and Sour Pork",
    aliases: ["sweet sour pork"],
    cuisine: "chinese",
    category: "Entree",
    typicalValue: 14,
    valueLow: 11,
    valueHigh: 17,
    fillFactor: 8,
    gramsPerUnit: 300,
  },
  {
    id: "chinese.sweet-sour-chicken",
    name: "Sweet and Sour Chicken",
    aliases: ["sweet sour chicken"],
    cuisine: "chinese",
    category: "Entree",
    typicalValue: 13,
    valueLow: 10,
    valueHigh: 16,
    fillFactor: 8,
    gramsPerUnit: 300,
  },
  {
    id: "chinese.mapo-tofu",
    name: "Mapo Tofu",
    aliases: ["ma po tofu", "ma pao tofu"],
    cuisine: "chinese",
    category: "Entree",
    typicalValue: 13,
    valueLow: 10,
    valueHigh: 16,
    fillFactor: 7,
    gramsPerUnit: 300,
  },
  {
    id: "chinese.lo-mein",
    name: "Lo Mein",
    aliases: ["chicken lo mein"],
    cuisine: "chinese",
    category: "Noodles",
    typicalValue: 12,
    valueLow: 9,
    valueHigh: 15,
    fillFactor: 8,
    gramsPerUnit: 350,
  },
  {
    id: "chinese.chow-mein",
    name: "Chow Mein",
    aliases: ["chicken chow mein"],
    cuisine: "chinese",
    category: "Noodles",
    typicalValue: 12,
    valueLow: 9,
    valueHigh: 15,
    fillFactor: 8,
    gramsPerUnit: 350,
  },
  {
    id: "chinese.singapore-noodles",
    name: "Singapore Noodles",
    aliases: ["singapore mei fun"],
    cuisine: "chinese",
    category: "Noodles",
    typicalValue: 13,
    valueLow: 10,
    valueHigh: 16,
    fillFactor: 8,
    gramsPerUnit: 350,
  },
  {
    id: "chinese.fried-rice",
    name: "Fried Rice",
    aliases: ["chicken fried rice", "house fried rice"],
    cuisine: "chinese",
    category: "Rice",
    typicalValue: 11,
    valueLow: 8,
    valueHigh: 14,
    fillFactor: 7,
    gramsPerUnit: 350,
  },
  {
    id: "chinese.yangzhou-fried-rice",
    name: "Yangzhou Fried Rice",
    aliases: ["yang chow fried rice"],
    cuisine: "chinese",
    category: "Rice",
    typicalValue: 13,
    valueLow: 10,
    valueHigh: 16,
    fillFactor: 7,
    gramsPerUnit: 350,
  },
  {
    id: "chinese.egg-roll",
    name: "Egg Roll",
    aliases: ["eggroll"],
    cuisine: "chinese",
    category: "Appetizer",
    typicalValue: 3,
    valueLow: 2,
    valueHigh: 4,
    fillFactor: 3,
    gramsPerUnit: 80,
  },
  {
    id: "chinese.spring-roll",
    name: "Spring Roll",
    aliases: ["veggie spring roll"],
    cuisine: "chinese",
    category: "Appetizer",
    typicalValue: 3,
    valueLow: 2,
    valueHigh: 4,
    fillFactor: 2,
    gramsPerUnit: 40,
  },
  {
    id: "chinese.crab-rangoon",
    name: "Crab Rangoon",
    aliases: ["cream cheese wonton"],
    cuisine: "chinese",
    category: "Appetizer",
    typicalValue: 2,
    valueLow: 1.5,
    valueHigh: 3,
    fillFactor: 2,
    gramsPerUnit: 20,
  },
  {
    id: "chinese.wonton-soup",
    name: "Wonton Soup",
    aliases: ["won ton soup"],
    cuisine: "chinese",
    category: "Soup",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 4,
    gramsPerUnit: 300,
  },
  {
    id: "chinese.hot-sour-soup",
    name: "Hot and Sour Soup",
    aliases: ["hot sour soup"],
    cuisine: "chinese",
    category: "Soup",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 4,
    gramsPerUnit: 300,
  },
  {
    id: "chinese.egg-drop-soup",
    name: "Egg Drop Soup",
    aliases: [],
    cuisine: "chinese",
    category: "Soup",
    typicalValue: 4,
    valueLow: 3,
    valueHigh: 6,
    fillFactor: 4,
    gramsPerUnit: 300,
  },
  {
    id: "chinese.peking-duck",
    name: "Peking Duck",
    aliases: ["beijing duck"],
    cuisine: "chinese",
    category: "Entree",
    typicalValue: 25,
    valueLow: 20,
    valueHigh: 35,
    fillFactor: 9,
    gramsPerUnit: 300,
  },
  {
    id: "chinese.salt-pepper-shrimp",
    name: "Salt and Pepper Shrimp",
    aliases: ["salt pepper shrimp"],
    cuisine: "chinese",
    category: "Entree",
    typicalValue: 18,
    valueLow: 15,
    valueHigh: 22,
    fillFactor: 7,
    gramsPerUnit: 220,
  },
  {
    id: "chinese.chow-fun",
    name: "Beef Chow Fun",
    aliases: ["chow fun", "ho fun"],
    cuisine: "chinese",
    category: "Noodles",
    typicalValue: 14,
    valueLow: 11,
    valueHigh: 17,
    fillFactor: 8,
    gramsPerUnit: 350,
  },
  {
    id: "chinese.dry-fried-green-beans",
    name: "Dry-Fried Green Beans",
    aliases: ["dry fried green beans", "green beans", "sichuan green beans"],
    cuisine: "chinese",
    category: "Vegetable",
    typicalValue: 11,
    valueLow: 9,
    valueHigh: 14,
    fillFactor: 5,
    gramsPerUnit: 120,
  },
  {
    id: "chinese.garlic-bok-choy",
    name: "Garlic Bok Choy",
    aliases: ["bok choy", "baby bok choy"],
    cuisine: "chinese",
    category: "Vegetable",
    typicalValue: 10,
    valueLow: 8,
    valueHigh: 12,
    fillFactor: 4,
    gramsPerUnit: 120,
  },

  // ─── Dim Sum ─────────────────────────────────────────────────────────
  {
    id: "dimsum.har-gow",
    name: "Har Gow",
    aliases: ["har gau", "shrimp dumpling", "shrimp dumplings"],
    cuisine: "dimsum",
    category: "Dumpling",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 3,
    gramsPerUnit: 100,
  },
  {
    id: "dimsum.siu-mai",
    name: "Siu Mai",
    aliases: ["shu mai", "shumai", "pork dumpling"],
    cuisine: "dimsum",
    category: "Dumpling",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 3,
    gramsPerUnit: 100,
  },
  {
    id: "dimsum.char-siu-bao",
    name: "Char Siu Bao",
    aliases: ["bbq pork bun", "cha siu bao", "steamed pork bun"],
    cuisine: "dimsum",
    category: "Bun",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 4,
    gramsPerUnit: 80,
  },
  {
    id: "dimsum.baked-char-siu-bao",
    name: "Baked Char Siu Bao",
    aliases: ["baked bbq pork bun", "baked pork bun"],
    cuisine: "dimsum",
    category: "Bun",
    typicalValue: 5.5,
    valueLow: 4.5,
    valueHigh: 7,
    fillFactor: 4,
    gramsPerUnit: 90,
  },
  {
    id: "dimsum.egg-tart",
    name: "Egg Tart",
    aliases: ["dan tat", "daan taat"],
    cuisine: "dimsum",
    category: "Dessert",
    typicalValue: 3,
    valueLow: 2,
    valueHigh: 4,
    fillFactor: 2,
    gramsPerUnit: 55,
  },
  {
    id: "dimsum.turnip-cake",
    name: "Turnip Cake",
    aliases: ["lo bak go", "daikon cake", "radish cake"],
    cuisine: "dimsum",
    category: "Small Plate",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 4,
    gramsPerUnit: 60,
  },
  {
    id: "dimsum.taro-cake",
    name: "Taro Cake",
    aliases: ["wu tau go"],
    cuisine: "dimsum",
    category: "Small Plate",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 4,
    gramsPerUnit: 60,
  },
  {
    id: "dimsum.chicken-feet",
    name: "Chicken Feet",
    aliases: ["phoenix claws", "fung zao"],
    cuisine: "dimsum",
    category: "Small Plate",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 140,
  },
  {
    id: "dimsum.congee",
    name: "Congee",
    aliases: ["jook", "rice porridge"],
    cuisine: "dimsum",
    category: "Rice",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 9,
    fillFactor: 6,
    gramsPerUnit: 350,
  },
  {
    id: "dimsum.rice-noodle-roll",
    name: "Rice Noodle Roll",
    aliases: ["cheung fun", "chee cheong fun"],
    cuisine: "dimsum",
    category: "Noodles",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 4,
    gramsPerUnit: 200,
  },
  {
    id: "dimsum.shrimp-rice-noodle-roll",
    name: "Shrimp Rice Noodle Roll",
    aliases: ["shrimp cheung fun", "har cheung fun"],
    cuisine: "dimsum",
    category: "Noodles",
    typicalValue: 7,
    valueLow: 6,
    valueHigh: 9,
    fillFactor: 5,
    gramsPerUnit: 220,
  },
  {
    id: "dimsum.xiao-long-bao",
    name: "Xiao Long Bao",
    aliases: ["soup dumpling", "soup dumplings", "xlb"],
    cuisine: "dimsum",
    category: "Dumpling",
    typicalValue: 9,
    valueLow: 7,
    valueHigh: 12,
    fillFactor: 4,
    gramsPerUnit: 120,
  },
  {
    id: "dimsum.potstickers",
    name: "Potstickers",
    aliases: ["pan fried dumpling", "guo tie", "jiaozi"],
    cuisine: "dimsum",
    category: "Dumpling",
    typicalValue: 7,
    valueLow: 5,
    valueHigh: 9,
    fillFactor: 4,
    gramsPerUnit: 120,
  },
  {
    id: "dimsum.sticky-rice-lotus-leaf",
    name: "Sticky Rice in Lotus Leaf",
    aliases: ["lo mai gai", "lotus leaf rice"],
    cuisine: "dimsum",
    category: "Rice",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 7,
    gramsPerUnit: 220,
  },
  {
    id: "dimsum.beef-rice-noodle-roll",
    name: "Beef Rice Noodle Roll",
    aliases: ["beef cheung fun"],
    cuisine: "dimsum",
    category: "Noodles",
    typicalValue: 7,
    valueLow: 6,
    valueHigh: 9,
    fillFactor: 5,
    gramsPerUnit: 220,
  },
  {
    id: "dimsum.pork-ribs-black-bean",
    name: "Pork Ribs with Black Bean",
    aliases: ["steamed pork ribs", "dou si pai gwat"],
    cuisine: "dimsum",
    category: "Small Plate",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 4,
    gramsPerUnit: 140,
  },
  {
    id: "dimsum.shrimp-toast",
    name: "Shrimp Toast",
    aliases: ["har toast"],
    cuisine: "dimsum",
    category: "Small Plate",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 4,
    gramsPerUnit: 30,
  },
  {
    id: "dimsum.fried-sesame-ball",
    name: "Fried Sesame Ball",
    aliases: ["jin deui", "sesame ball"],
    cuisine: "dimsum",
    category: "Dessert",
    typicalValue: 3,
    valueLow: 2,
    valueHigh: 4,
    fillFactor: 3,
    gramsPerUnit: 50,
  },
  {
    id: "dimsum.mango-pudding",
    name: "Mango Pudding",
    aliases: [],
    cuisine: "dimsum",
    category: "Dessert",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 150,
  },
  {
    id: "dimsum.pan-fried-leek-dumpling",
    name: "Pan-Fried Leek Dumpling",
    aliases: ["pan fried leek dumpling", "leek dumpling", "chives dumpling"],
    cuisine: "dimsum",
    category: "Dumpling",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 4,
    gramsPerUnit: 40,
  },
  {
    id: "dimsum.stuffed-eggplant",
    name: "Stuffed Eggplant",
    aliases: ["eggplant with shrimp"],
    cuisine: "dimsum",
    category: "Small Plate",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 4,
    gramsPerUnit: 60,
  },
  {
    id: "dimsum.stuffed-tofu",
    name: "Stuffed Tofu",
    aliases: ["tofu with shrimp"],
    cuisine: "dimsum",
    category: "Small Plate",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 4,
    gramsPerUnit: 60,
  },
  {
    id: "dimsum.fried-tofu-skin-roll",
    name: "Fried Tofu Skin Roll",
    aliases: ["tofu skin roll", "fu pei gyun"],
    cuisine: "dimsum",
    category: "Small Plate",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 4,
    gramsPerUnit: 50,
  },
  {
    id: "dimsum.water-spinach",
    name: "Stir-Fried Water Spinach",
    aliases: ["stir fried water spinach", "water spinach", "ong choy"],
    cuisine: "dimsum",
    category: "Vegetable",
    typicalValue: 10,
    valueLow: 8,
    valueHigh: 13,
    fillFactor: 4,
    gramsPerUnit: 150,
  },
  {
    id: "dimsum.salt-pepper-squid",
    name: "Salt and Pepper Squid",
    aliases: ["salt pepper squid", "fried squid"],
    cuisine: "dimsum",
    category: "Small Plate",
    typicalValue: 12,
    valueLow: 10,
    valueHigh: 15,
    fillFactor: 5,
    gramsPerUnit: 200,
  },

  // ─── Hot Pot ────────────────────────────────────────────────────────
  {
    id: "hotpot.sliced-beef",
    name: "Sliced Beef",
    aliases: ["beef slices", "hot pot beef"],
    cuisine: "hotpot",
    category: "Protein",
    typicalValue: 14,
    valueLow: 11,
    valueHigh: 17,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "hotpot.fatty-beef",
    name: "Fatty Beef",
    aliases: ["fatty beef rolls", "feiniu"],
    cuisine: "hotpot",
    category: "Protein",
    typicalValue: 15,
    valueLow: 12,
    valueHigh: 18,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "hotpot.lamb-rolls",
    name: "Lamb Rolls",
    aliases: ["sliced lamb", "hot pot lamb"],
    cuisine: "hotpot",
    category: "Protein",
    typicalValue: 14,
    valueLow: 11,
    valueHigh: 17,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "hotpot.pork-belly",
    name: "Pork Belly Slices",
    aliases: ["sliced pork belly", "hot pot pork"],
    cuisine: "hotpot",
    category: "Protein",
    typicalValue: 12,
    valueLow: 10,
    valueHigh: 15,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "hotpot.fish-balls",
    name: "Fish Balls",
    aliases: ["fishball"],
    cuisine: "hotpot",
    category: "Protein",
    typicalValue: 8,
    valueLow: 6,
    valueHigh: 10,
    fillFactor: 3,
    gramsPerUnit: 120,
  },
  {
    id: "hotpot.beef-balls",
    name: "Beef Balls",
    aliases: ["beef ball"],
    cuisine: "hotpot",
    category: "Protein",
    typicalValue: 9,
    valueLow: 7,
    valueHigh: 11,
    fillFactor: 3,
    gramsPerUnit: 120,
  },
  {
    id: "hotpot.shrimp-paste",
    name: "Shrimp Paste",
    aliases: ["har mi"],
    cuisine: "hotpot",
    category: "Protein",
    typicalValue: 10,
    valueLow: 8,
    valueHigh: 13,
    fillFactor: 4,
    gramsPerUnit: 100,
  },
  {
    id: "hotpot.beef-tripe",
    name: "Beef Tripe",
    aliases: ["honeycomb tripe"],
    cuisine: "hotpot",
    category: "Offal",
    typicalValue: 11,
    valueLow: 9,
    valueHigh: 14,
    fillFactor: 3,
    gramsPerUnit: 100,
  },
  {
    id: "hotpot.duck-blood",
    name: "Duck Blood",
    aliases: ["duck blood tofu"],
    cuisine: "hotpot",
    category: "Offal",
    typicalValue: 8,
    valueLow: 6,
    valueHigh: 10,
    fillFactor: 3,
    gramsPerUnit: 150,
  },
  {
    id: "hotpot.enoki",
    name: "Enoki Mushrooms",
    aliases: ["enoki", "enokitake"],
    cuisine: "hotpot",
    category: "Vegetable",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 150,
  },
  {
    id: "hotpot.shiitake",
    name: "Shiitake Mushrooms",
    aliases: ["shiitake"],
    cuisine: "hotpot",
    category: "Vegetable",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 3,
    gramsPerUnit: 120,
  },
  {
    id: "hotpot.napa-cabbage",
    name: "Napa Cabbage",
    aliases: ["napa", "chinese cabbage"],
    cuisine: "hotpot",
    category: "Vegetable",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 200,
  },
  {
    id: "hotpot.watercress",
    name: "Watercress",
    aliases: [],
    cuisine: "hotpot",
    category: "Vegetable",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 120,
  },
  {
    id: "hotpot.tofu",
    name: "Tofu",
    aliases: ["hot pot tofu"],
    cuisine: "hotpot",
    category: "Vegetable",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 180,
  },
  {
    id: "hotpot.frozen-tofu",
    name: "Frozen Tofu",
    aliases: [],
    cuisine: "hotpot",
    category: "Vegetable",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 150,
  },
  {
    id: "hotpot.glass-noodles",
    name: "Glass Noodles",
    aliases: ["bean thread noodles", "fensi"],
    cuisine: "hotpot",
    category: "Starch",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "hotpot.udon",
    name: "Udon",
    aliases: ["hot pot udon", "udon noodles"],
    cuisine: "hotpot",
    category: "Starch",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 6,
    gramsPerUnit: 200,
  },
  {
    id: "hotpot.rice-cake",
    name: "Rice Cake",
    aliases: ["nian gao", "tteok"],
    cuisine: "hotpot",
    category: "Starch",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "hotpot.mala-broth",
    name: "Mala Broth",
    aliases: ["spicy broth", "sichuan broth", "ma la broth"],
    cuisine: "hotpot",
    category: "Broth",
    typicalValue: 6,
    valueLow: 4,
    valueHigh: 8,
    fillFactor: 2,
    gramsPerUnit: 0,
  },
  {
    id: "hotpot.tomato-broth",
    name: "Tomato Broth",
    aliases: [],
    cuisine: "hotpot",
    category: "Broth",
    typicalValue: 6,
    valueLow: 4,
    valueHigh: 8,
    fillFactor: 2,
    gramsPerUnit: 0,
  },

  // ─── Brazilian / Churrasco ───────────────────────────────────────────
  {
    id: "brazilian.picanha",
    name: "Picanha",
    aliases: ["sirloin cap", "coulotte"],
    cuisine: "brazilian",
    category: "Beef",
    typicalValue: 22,
    valueLow: 18,
    valueHigh: 28,
    fillFactor: 7,
    gramsPerUnit: 120,
  },
  {
    id: "brazilian.alcatra",
    name: "Alcatra",
    aliases: ["top sirloin"],
    cuisine: "brazilian",
    category: "Beef",
    typicalValue: 18,
    valueLow: 15,
    valueHigh: 22,
    fillFactor: 7,
    gramsPerUnit: 120,
  },
  {
    id: "brazilian.ribeye",
    name: "Ribeye",
    aliases: ["rib eye"],
    cuisine: "brazilian",
    category: "Beef",
    typicalValue: 24,
    valueLow: 20,
    valueHigh: 30,
    fillFactor: 8,
    gramsPerUnit: 120,
  },
  {
    id: "brazilian.filet-mignon-bacon",
    name: "Bacon-Wrapped Filet Mignon",
    aliases: ["bacon wrapped filet mignon", "filet mignon", "bacon wrapped filet"],
    cuisine: "brazilian",
    category: "Beef",
    typicalValue: 26,
    valueLow: 22,
    valueHigh: 32,
    fillFactor: 7,
    gramsPerUnit: 100,
  },
  {
    id: "brazilian.fraldinha",
    name: "Fraldinha",
    aliases: ["flank steak", "bottom sirloin"],
    cuisine: "brazilian",
    category: "Beef",
    typicalValue: 19,
    valueLow: 16,
    valueHigh: 24,
    fillFactor: 6,
    gramsPerUnit: 120,
  },
  {
    id: "brazilian.beef-ancho",
    name: "Beef Ancho",
    aliases: ["ancho", "prime rib"],
    cuisine: "brazilian",
    category: "Beef",
    typicalValue: 22,
    valueLow: 18,
    valueHigh: 28,
    fillFactor: 7,
    gramsPerUnit: 120,
  },
  {
    id: "brazilian.chicken-heart",
    name: "Chicken Hearts",
    aliases: ["chicken heart", "coracao de frango"],
    cuisine: "brazilian",
    category: "Poultry",
    typicalValue: 10,
    valueLow: 8,
    valueHigh: 13,
    fillFactor: 3,
    gramsPerUnit: 15,
  },
  {
    id: "brazilian.chicken-leg",
    name: "Chicken Leg",
    aliases: ["frango"],
    cuisine: "brazilian",
    category: "Poultry",
    typicalValue: 11,
    valueLow: 9,
    valueHigh: 14,
    fillFactor: 6,
    gramsPerUnit: 120,
  },
  {
    id: "brazilian.chicken-wrapped-bacon",
    name: "Bacon-Wrapped Chicken",
    aliases: ["bacon wrapped chicken"],
    cuisine: "brazilian",
    category: "Poultry",
    typicalValue: 13,
    valueLow: 10,
    valueHigh: 16,
    fillFactor: 6,
    gramsPerUnit: 80,
  },
  {
    id: "brazilian.linguica",
    name: "Linguiça",
    aliases: ["brazilian sausage"],
    cuisine: "brazilian",
    category: "Pork",
    typicalValue: 11,
    valueLow: 9,
    valueHigh: 14,
    fillFactor: 5,
    gramsPerUnit: 40,
  },
  {
    id: "brazilian.pork-ribs",
    name: "Pork Ribs",
    aliases: ["costela de porco"],
    cuisine: "brazilian",
    category: "Pork",
    typicalValue: 16,
    valueLow: 13,
    valueHigh: 20,
    fillFactor: 7,
    gramsPerUnit: 80,
  },
  {
    id: "brazilian.lamb-chop",
    name: "Lamb Chop",
    aliases: ["lamb chops", "cordeiro"],
    cuisine: "brazilian",
    category: "Lamb",
    typicalValue: 22,
    valueLow: 18,
    valueHigh: 28,
    fillFactor: 6,
    gramsPerUnit: 90,
  },
  {
    id: "brazilian.leg-of-lamb",
    name: "Leg of Lamb",
    aliases: ["perna de cordeiro"],
    cuisine: "brazilian",
    category: "Lamb",
    typicalValue: 22,
    valueLow: 18,
    valueHigh: 28,
    fillFactor: 7,
    gramsPerUnit: 120,
  },
  {
    id: "brazilian.pao-de-queijo",
    name: "Pão de Queijo",
    aliases: ["brazilian cheese bread", "cheese bread"],
    cuisine: "brazilian",
    category: "Side",
    typicalValue: 4,
    valueLow: 3,
    valueHigh: 6,
    fillFactor: 3,
    gramsPerUnit: 20,
  },
  {
    id: "brazilian.farofa",
    name: "Farofa",
    aliases: ["toasted cassava flour"],
    cuisine: "brazilian",
    category: "Side",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 60,
  },

  // ─── Indian Buffet ───────────────────────────────────────────────────
  {
    id: "indian.chicken-tikka-masala",
    name: "Chicken Tikka Masala",
    aliases: ["tikka masala", "ctm"],
    cuisine: "indian",
    category: "Curry",
    typicalValue: 16,
    valueLow: 13,
    valueHigh: 19,
    fillFactor: 8,
    gramsPerUnit: 300,
  },
  {
    id: "indian.butter-chicken",
    name: "Butter Chicken",
    aliases: ["murgh makhani"],
    cuisine: "indian",
    category: "Curry",
    typicalValue: 16,
    valueLow: 13,
    valueHigh: 19,
    fillFactor: 8,
    gramsPerUnit: 300,
  },
  {
    id: "indian.chicken-vindaloo",
    name: "Chicken Vindaloo",
    aliases: ["vindaloo"],
    cuisine: "indian",
    category: "Curry",
    typicalValue: 16,
    valueLow: 13,
    valueHigh: 19,
    fillFactor: 8,
    gramsPerUnit: 300,
  },
  {
    id: "indian.lamb-vindaloo",
    name: "Lamb Vindaloo",
    aliases: [],
    cuisine: "indian",
    category: "Curry",
    typicalValue: 18,
    valueLow: 15,
    valueHigh: 22,
    fillFactor: 8,
    gramsPerUnit: 300,
  },
  {
    id: "indian.lamb-rogan-josh",
    name: "Lamb Rogan Josh",
    aliases: ["rogan josh"],
    cuisine: "indian",
    category: "Curry",
    typicalValue: 18,
    valueLow: 15,
    valueHigh: 22,
    fillFactor: 8,
    gramsPerUnit: 300,
  },
  {
    id: "indian.saag-paneer",
    name: "Saag Paneer",
    aliases: ["palak paneer", "spinach paneer"],
    cuisine: "indian",
    category: "Curry",
    typicalValue: 14,
    valueLow: 11,
    valueHigh: 17,
    fillFactor: 7,
    gramsPerUnit: 300,
  },
  {
    id: "indian.chana-masala",
    name: "Chana Masala",
    aliases: ["chickpea curry"],
    cuisine: "indian",
    category: "Curry",
    typicalValue: 12,
    valueLow: 10,
    valueHigh: 15,
    fillFactor: 7,
    gramsPerUnit: 300,
  },
  {
    id: "indian.dal-makhani",
    name: "Dal Makhani",
    aliases: ["daal makhani", "black lentil"],
    cuisine: "indian",
    category: "Curry",
    typicalValue: 12,
    valueLow: 10,
    valueHigh: 15,
    fillFactor: 7,
    gramsPerUnit: 300,
  },
  {
    id: "indian.aloo-gobi",
    name: "Aloo Gobi",
    aliases: ["potato cauliflower"],
    cuisine: "indian",
    category: "Curry",
    typicalValue: 12,
    valueLow: 10,
    valueHigh: 15,
    fillFactor: 7,
    gramsPerUnit: 300,
  },
  {
    id: "indian.chicken-biryani",
    name: "Chicken Biryani",
    aliases: ["biryani"],
    cuisine: "indian",
    category: "Rice",
    typicalValue: 16,
    valueLow: 13,
    valueHigh: 19,
    fillFactor: 9,
    gramsPerUnit: 400,
  },
  {
    id: "indian.lamb-biryani",
    name: "Lamb Biryani",
    aliases: [],
    cuisine: "indian",
    category: "Rice",
    typicalValue: 18,
    valueLow: 15,
    valueHigh: 22,
    fillFactor: 9,
    gramsPerUnit: 400,
  },
  {
    id: "indian.naan",
    name: "Naan",
    aliases: ["plain naan"],
    cuisine: "indian",
    category: "Bread",
    typicalValue: 3,
    valueLow: 2,
    valueHigh: 5,
    fillFactor: 4,
    gramsPerUnit: 90,
  },
  {
    id: "indian.garlic-naan",
    name: "Garlic Naan",
    aliases: [],
    cuisine: "indian",
    category: "Bread",
    typicalValue: 4,
    valueLow: 3,
    valueHigh: 6,
    fillFactor: 4,
    gramsPerUnit: 90,
  },
  {
    id: "indian.samosa",
    name: "Samosa",
    aliases: ["vegetable samosa"],
    cuisine: "indian",
    category: "Appetizer",
    typicalValue: 3,
    valueLow: 2,
    valueHigh: 4,
    fillFactor: 3,
    gramsPerUnit: 60,
  },
  {
    id: "indian.pakora",
    name: "Pakora",
    aliases: ["vegetable pakora", "onion pakora"],
    cuisine: "indian",
    category: "Appetizer",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 3,
    gramsPerUnit: 20,
  },
  {
    id: "indian.tandoori-chicken",
    name: "Tandoori Chicken",
    aliases: [],
    cuisine: "indian",
    category: "Entree",
    typicalValue: 16,
    valueLow: 13,
    valueHigh: 19,
    fillFactor: 7,
    gramsPerUnit: 250,
  },
  {
    id: "indian.chicken-tikka",
    name: "Chicken Tikka",
    aliases: [],
    cuisine: "indian",
    category: "Appetizer",
    typicalValue: 11,
    valueLow: 9,
    valueHigh: 14,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "indian.gulab-jamun",
    name: "Gulab Jamun",
    aliases: [],
    cuisine: "indian",
    category: "Dessert",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 40,
  },
  {
    id: "indian.mango-lassi",
    name: "Mango Lassi",
    aliases: ["lassi"],
    cuisine: "indian",
    category: "Drink",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 240,
  },
  {
    id: "indian.basmati-rice",
    name: "Basmati Rice",
    aliases: ["basmati"],
    cuisine: "indian",
    category: "Rice",
    typicalValue: 4,
    valueLow: 3,
    valueHigh: 6,
    fillFactor: 5,
    gramsPerUnit: 200,
  },

  // ─── Pizza ───────────────────────────────────────────────────────────
  {
    id: "pizza.cheese-slice",
    name: "Cheese Slice",
    aliases: ["cheese pizza slice", "plain slice"],
    cuisine: "pizza",
    category: "Slice",
    typicalValue: 3.5,
    valueLow: 2.5,
    valueHigh: 5,
    fillFactor: 4,
    gramsPerUnit: 120,
  },
  {
    id: "pizza.pepperoni-slice",
    name: "Pepperoni Slice",
    aliases: ["pepperoni pizza slice"],
    cuisine: "pizza",
    category: "Slice",
    typicalValue: 4,
    valueLow: 3,
    valueHigh: 5.5,
    fillFactor: 4,
    gramsPerUnit: 120,
  },
  {
    id: "pizza.supreme-slice",
    name: "Supreme Slice",
    aliases: ["supreme pizza slice"],
    cuisine: "pizza",
    category: "Slice",
    typicalValue: 4.5,
    valueLow: 3.5,
    valueHigh: 6,
    fillFactor: 5,
    gramsPerUnit: 120,
  },
  {
    id: "pizza.sausage-slice",
    name: "Sausage Slice",
    aliases: ["sausage pizza slice"],
    cuisine: "pizza",
    category: "Slice",
    typicalValue: 4,
    valueLow: 3,
    valueHigh: 5.5,
    fillFactor: 4,
    gramsPerUnit: 120,
  },
  {
    id: "pizza.hawaiian-slice",
    name: "Hawaiian Slice",
    aliases: ["hawaiian pizza slice"],
    cuisine: "pizza",
    category: "Slice",
    typicalValue: 4.5,
    valueLow: 3.5,
    valueHigh: 6,
    fillFactor: 5,
    gramsPerUnit: 120,
  },
  {
    id: "pizza.white-slice",
    name: "White Pizza Slice",
    aliases: ["white slice", "bianca slice"],
    cuisine: "pizza",
    category: "Slice",
    typicalValue: 4.5,
    valueLow: 3.5,
    valueHigh: 6,
    fillFactor: 4,
    gramsPerUnit: 120,
  },
  {
    id: "pizza.margherita-slice",
    name: "Margherita Slice",
    aliases: ["margherita pizza slice"],
    cuisine: "pizza",
    category: "Slice",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 6.5,
    fillFactor: 4,
    gramsPerUnit: 120,
  },
  {
    id: "pizza.whole-cheese-pie",
    name: "Whole Cheese Pizza",
    aliases: ["whole cheese pie", "large cheese pizza"],
    cuisine: "pizza",
    category: "Whole Pie",
    typicalValue: 18,
    valueLow: 14,
    valueHigh: 24,
    fillFactor: 10,
    gramsPerUnit: 800,
  },
  {
    id: "pizza.chicken-wings",
    name: "Chicken Wings",
    aliases: ["wings", "buffalo wings"],
    cuisine: "pizza",
    category: "Appetizer",
    typicalValue: 12,
    valueLow: 9,
    valueHigh: 15,
    fillFactor: 5,
    gramsPerUnit: 30,
  },
  {
    id: "pizza.garlic-knots",
    name: "Garlic Knots",
    aliases: ["breadsticks", "garlic bread"],
    cuisine: "pizza",
    category: "Side",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 25,
  },

  // ─── Seafood Buffet ──────────────────────────────────────────────────
  {
    id: "seafood.snow-crab-legs",
    name: "Snow Crab Legs",
    aliases: ["snow crab"],
    cuisine: "seafood",
    category: "Shellfish",
    typicalValue: 30,
    valueLow: 24,
    valueHigh: 38,
    fillFactor: 7,
    gramsPerUnit: 300,
  },
  {
    id: "seafood.king-crab-legs",
    name: "King Crab Legs",
    aliases: ["king crab", "alaskan king crab"],
    cuisine: "seafood",
    category: "Shellfish",
    typicalValue: 55,
    valueLow: 45,
    valueHigh: 75,
    fillFactor: 8,
    gramsPerUnit: 400,
  },
  {
    id: "seafood.lobster-tail",
    name: "Lobster Tail",
    aliases: [],
    cuisine: "seafood",
    category: "Shellfish",
    typicalValue: 28,
    valueLow: 22,
    valueHigh: 38,
    fillFactor: 6,
    gramsPerUnit: 170,
  },
  {
    id: "seafood.shrimp-cocktail",
    name: "Shrimp Cocktail",
    aliases: ["cocktail shrimp"],
    cuisine: "seafood",
    category: "Shellfish",
    typicalValue: 14,
    valueLow: 11,
    valueHigh: 18,
    fillFactor: 3,
    gramsPerUnit: 15,
  },
  {
    id: "seafood.peel-eat-shrimp",
    name: "Peel and Eat Shrimp",
    aliases: ["peel eat shrimp"],
    cuisine: "seafood",
    category: "Shellfish",
    typicalValue: 13,
    valueLow: 10,
    valueHigh: 17,
    fillFactor: 3,
    gramsPerUnit: 10,
  },
  {
    id: "seafood.oyster-raw",
    name: "Raw Oyster",
    aliases: ["oyster", "oysters on the half shell"],
    cuisine: "seafood",
    category: "Shellfish",
    typicalValue: 3.5,
    valueLow: 2.5,
    valueHigh: 5,
    fillFactor: 1,
    gramsPerUnit: 25,
  },
  {
    id: "seafood.mussels",
    name: "Mussels",
    aliases: ["steamed mussels"],
    cuisine: "seafood",
    category: "Shellfish",
    typicalValue: 14,
    valueLow: 11,
    valueHigh: 18,
    fillFactor: 6,
    gramsPerUnit: 200,
  },
  {
    id: "seafood.clams",
    name: "Clams",
    aliases: ["steamed clams", "littleneck clams"],
    cuisine: "seafood",
    category: "Shellfish",
    typicalValue: 14,
    valueLow: 11,
    valueHigh: 18,
    fillFactor: 5,
    gramsPerUnit: 200,
  },
  {
    id: "seafood.fried-calamari",
    name: "Fried Calamari",
    aliases: ["calamari"],
    cuisine: "seafood",
    category: "Appetizer",
    typicalValue: 13,
    valueLow: 10,
    valueHigh: 16,
    fillFactor: 5,
    gramsPerUnit: 180,
  },
  {
    id: "seafood.fish-and-chips",
    name: "Fish and Chips",
    aliases: ["fish n chips"],
    cuisine: "seafood",
    category: "Entree",
    typicalValue: 17,
    valueLow: 14,
    valueHigh: 21,
    fillFactor: 8,
    gramsPerUnit: 400,
  },
  {
    id: "seafood.grilled-salmon",
    name: "Grilled Salmon",
    aliases: ["salmon fillet"],
    cuisine: "seafood",
    category: "Entree",
    typicalValue: 22,
    valueLow: 18,
    valueHigh: 28,
    fillFactor: 8,
    gramsPerUnit: 170,
  },
  {
    id: "seafood.scallops",
    name: "Scallops",
    aliases: ["seared scallops"],
    cuisine: "seafood",
    category: "Shellfish",
    typicalValue: 24,
    valueLow: 19,
    valueHigh: 30,
    fillFactor: 6,
    gramsPerUnit: 25,
  },
  {
    id: "seafood.crawfish-boil",
    name: "Crawfish",
    aliases: ["crawfish boil", "crayfish"],
    cuisine: "seafood",
    category: "Shellfish",
    typicalValue: 16,
    valueLow: 12,
    valueHigh: 22,
    fillFactor: 4,
    gramsPerUnit: 450,
  },
  {
    id: "seafood.ceviche",
    name: "Ceviche",
    aliases: [],
    cuisine: "seafood",
    category: "Appetizer",
    typicalValue: 13,
    valueLow: 10,
    valueHigh: 17,
    fillFactor: 5,
    gramsPerUnit: 180,
  },
  {
    id: "seafood.clam-chowder",
    name: "Clam Chowder",
    aliases: ["new england clam chowder"],
    cuisine: "seafood",
    category: "Soup",
    typicalValue: 8,
    valueLow: 6,
    valueHigh: 11,
    fillFactor: 5,
    gramsPerUnit: 300,
  },

  // ─── Dessert ─────────────────────────────────────────────────────────
  {
    id: "dessert.mochi-ice-cream",
    name: "Mochi Ice Cream",
    aliases: ["mochi"],
    cuisine: "dessert",
    category: "Frozen",
    typicalValue: 3,
    valueLow: 2,
    valueHigh: 4,
    fillFactor: 2,
    gramsPerUnit: 40,
  },
  {
    id: "dessert.tiramisu",
    name: "Tiramisu",
    aliases: [],
    cuisine: "dessert",
    category: "Cake",
    typicalValue: 9,
    valueLow: 7,
    valueHigh: 12,
    fillFactor: 5,
    gramsPerUnit: 120,
  },
  {
    id: "dessert.cheesecake-slice",
    name: "Cheesecake Slice",
    aliases: ["cheesecake", "new york cheesecake"],
    cuisine: "dessert",
    category: "Cake",
    typicalValue: 9,
    valueLow: 7,
    valueHigh: 12,
    fillFactor: 5,
    gramsPerUnit: 130,
  },
  {
    id: "dessert.chocolate-cake-slice",
    name: "Chocolate Cake Slice",
    aliases: ["chocolate cake"],
    cuisine: "dessert",
    category: "Cake",
    typicalValue: 8,
    valueLow: 6,
    valueHigh: 11,
    fillFactor: 5,
    gramsPerUnit: 120,
  },
  {
    id: "dessert.creme-brulee",
    name: "Crème Brûlée",
    aliases: ["creme brulée"],
    cuisine: "dessert",
    category: "Custard",
    typicalValue: 9,
    valueLow: 7,
    valueHigh: 12,
    fillFactor: 4,
    gramsPerUnit: 150,
  },
  {
    id: "dessert.flan",
    name: "Flan",
    aliases: ["caramel flan"],
    cuisine: "dessert",
    category: "Custard",
    typicalValue: 7,
    valueLow: 5,
    valueHigh: 10,
    fillFactor: 4,
    gramsPerUnit: 120,
  },
  {
    id: "dessert.ice-cream-scoop",
    name: "Ice Cream Scoop",
    aliases: ["ice cream", "scoop of ice cream"],
    cuisine: "dessert",
    category: "Frozen",
    typicalValue: 4,
    valueLow: 3,
    valueHigh: 6,
    fillFactor: 3,
    gramsPerUnit: 70,
  },
  {
    id: "dessert.gelato",
    name: "Gelato",
    aliases: ["italian gelato"],
    cuisine: "dessert",
    category: "Frozen",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 60,
  },
  {
    id: "dessert.brownie",
    name: "Brownie",
    aliases: ["chocolate brownie"],
    cuisine: "dessert",
    category: "Baked",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 4,
    gramsPerUnit: 80,
  },
  {
    id: "dessert.cannoli",
    name: "Cannoli",
    aliases: ["cannolo"],
    cuisine: "dessert",
    category: "Baked",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 70,
  },
  {
    id: "dessert.tres-leches",
    name: "Tres Leches",
    aliases: ["tres leches cake"],
    cuisine: "dessert",
    category: "Cake",
    typicalValue: 8,
    valueLow: 6,
    valueHigh: 11,
    fillFactor: 5,
    gramsPerUnit: 150,
  },
  {
    id: "dessert.baklava",
    name: "Baklava",
    aliases: [],
    cuisine: "dessert",
    category: "Baked",
    typicalValue: 5,
    valueLow: 4,
    valueHigh: 7,
    fillFactor: 3,
    gramsPerUnit: 45,
  },
  {
    id: "dessert.churros",
    name: "Churros",
    aliases: ["churro"],
    cuisine: "dessert",
    category: "Fried",
    typicalValue: 6,
    valueLow: 4,
    valueHigh: 8,
    fillFactor: 4,
    gramsPerUnit: 30,
  },
  {
    id: "dessert.panna-cotta",
    name: "Panna Cotta",
    aliases: [],
    cuisine: "dessert",
    category: "Custard",
    typicalValue: 8,
    valueLow: 6,
    valueHigh: 11,
    fillFactor: 4,
    gramsPerUnit: 130,
  },
  {
    id: "dessert.jalapeno-popper",
    name: "Jalapeño Popper",
    aliases: [],
    cuisine: "other",
    category: "Appetizer",
    typicalValue: 6,
    valueLow: 5,
    valueHigh: 8,
    fillFactor: 3,
    gramsPerUnit: 25,
  },
  {
    id: "dessert.fruit-salad",
    name: "Fruit Salad",
    aliases: ["fresh fruit"],
    cuisine: "dessert",
    category: "Fruit",
    typicalValue: 6,
    valueLow: 4,
    valueHigh: 8,
    fillFactor: 3,
    gramsPerUnit: 180,
  },
];

/**
 * Normalize a string for matching: lowercase, strip diacritics, collapse
 * whitespace. Pure, sync.
 */
function normalize(input: string): string {
  return input
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .replace(/\s+/g, " ")
    .trim();
}

interface ScoredEntry {
  readonly entry: SeedEntry;
  readonly score: number;
}

function scoreEntry(entry: SeedEntry, query: string): number {
  const name = normalize(entry.name);
  if (name === query) return 100;

  for (const alias of entry.aliases) {
    if (normalize(alias) === query) return 90;
  }

  if (name.startsWith(query)) return 70;

  for (const alias of entry.aliases) {
    if (normalize(alias).startsWith(query)) return 60;
  }

  if (name.includes(query)) return 40;

  for (const alias of entry.aliases) {
    if (normalize(alias).includes(query)) return 30;
  }

  return 0;
}

function cuisineRank(cuisine: Cuisine): number {
  return CUISINE_RANK.get(cuisine) ?? CUISINE_PRIORITY.length;
}

/**
 * Find seed catalog entries matching the query, highest score first.
 *
 * - Empty query (after normalization) returns `[]`.
 * - `limit <= 0` returns `[]`.
 * - Score weights: exact name 100, exact alias 90, name starts-with 70,
 *   alias starts-with 60, name includes 40, alias includes 30.
 * - Tie-break by cuisine priority (kbbq → sushi → chinese → dimsum → hotpot
 *   → brazilian → indian → pizza → seafood → dessert → other), then by
 *   `name` alphabetically.
 * - Pure, synchronous, no side effects.
 */
export function findSeedMatches(query: string, limit: number): SeedEntry[] {
  if (limit <= 0) return [];
  const normalizedQuery = normalize(query);
  if (normalizedQuery === "") return [];

  const scored: ScoredEntry[] = [];
  for (const entry of SEED_CATALOG) {
    const score = scoreEntry(entry, normalizedQuery);
    if (score > 0) {
      scored.push({ entry, score });
    }
  }

  scored.sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    const cuisineDiff = cuisineRank(a.entry.cuisine) - cuisineRank(b.entry.cuisine);
    if (cuisineDiff !== 0) return cuisineDiff;
    return a.entry.name.localeCompare(b.entry.name);
  });

  return scored.slice(0, limit).map((s) => s.entry);
}
